services:
  byos-node-lite:
    build: .
    ports:
      - "3000:3000"
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - PUBLIC_URL_ORIGIN=${PUBLIC_URL_ORIGIN}
      - BYOS_DEVICE_MAC=${BYOS_DEVICE_MAC}
      - BYOS_DEVICE_ACCESS_TOKEN=${BYOS_DEVICE_ACCESS_TOKEN}
    restart: unless-stopped
